version: '3.8'

services:
  app:
    image: ma_super_app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      DATABASE_HOST: mysql
      DATABASE_PORT: 3306
      DATABASE_USERNAME: root
      DATABASE_PASSWORD: rootpassword
      DATABASE_NAME: testdb
    depends_on:
      - mysql
    networks:
      - backend
      - frontend

  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: testdb
    networks:
      - backend

networks:
  backend:
  frontend:

